#!/bin/bash

echo "⚙️  Create databases"

psql --username $POSTGRES_USER <<-EOSQL 2>/dev/null
    CREATE DATABASE "$POSTGRES_API_DB";
    CREATE DATABASE "$POSTGRES_APP_DB";
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_API_DB" TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_APP_DB" TO $POSTGRES_USER;
EOSQL

echo "✅ Databases created"
